SELECT * FROM <http://localhost:8080/fuseki/Izvestaj/data/metadata> where{
    ?izvestaj <http://www.pijz.rs/izvestajbrojZalbiOdluka> ?brojZalbiOdluka .
    FILTER(CONTAINS(UCASE(str(?brojZalbiOdluka)), UCASE("{{brojZalbiOdluka}}"))).
}