SELECT * FROM <http://localhost:8080/fuseki/ZalbaCutanje/data/metadata> where{
    ?zalbaCutanje <http://www.pijz.rs/commonime> ?ime .
    ?zalbaCutanje <http://www.pijz.rs/commonprezime> ?prezime .
    FILTER(CONTAINS(UCASE(str(?ime)), UCASE("{{ime}}"))
    && CONTAINS(UCASE(str(?prezime)), UCASE("{{prezime}}"))).
}