//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 01:26:56 PM CET 
//


package rs.ijz.server.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ijz.server.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ijz.server.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResenjeZalbaOsnovana }
     * 
     */
    public ResenjeZalbaOsnovana createResenjeZalbaOsnovana() {
        return new ResenjeZalbaOsnovana();
    }

    /**
     * Create an instance of {@link Stav }
     * 
     */
    public Stav createStav() {
        return new Stav();
    }

    /**
     * Create an instance of {@link ResenjeZalbaOsnovana.Obrazlozenje }
     * 
     */
    public ResenjeZalbaOsnovana.Obrazlozenje createResenjeZalbaOsnovanaObrazlozenje() {
        return new ResenjeZalbaOsnovana.Obrazlozenje();
    }

    /**
     * Create an instance of {@link FizickoLice }
     * 
     */
    public FizickoLice createFizickoLice() {
        return new FizickoLice();
    }

    /**
     * Create an instance of {@link PravnoLice }
     * 
     */
    public PravnoLice createPravnoLice() {
        return new PravnoLice();
    }

    /**
     * Create an instance of {@link ResenjeZalbaOsnovana.Dispozitiv }
     * 
     */
    public ResenjeZalbaOsnovana.Dispozitiv createResenjeZalbaOsnovanaDispozitiv() {
        return new ResenjeZalbaOsnovana.Dispozitiv();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link Tuzba }
     * 
     */
    public Tuzba createTuzba() {
        return new Tuzba();
    }

    /**
     * Create an instance of {@link Stav.Dokument }
     * 
     */
    public Stav.Dokument createStavDokument() {
        return new Stav.Dokument();
    }

    /**
     * Create an instance of {@link ResenjeZalbaOsnovana.Obrazlozenje.Paragraf }
     * 
     */
    public ResenjeZalbaOsnovana.Obrazlozenje.Paragraf createResenjeZalbaOsnovanaObrazlozenjeParagraf() {
        return new ResenjeZalbaOsnovana.Obrazlozenje.Paragraf();
    }

}
