//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.04 at 06:30:16 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(xmlns = {
        @XmlNs(prefix = "cmn", namespaceURI = "http://www.pijz.rs/common"),
        @XmlNs(prefix = "o", namespaceURI = "http://www.pijz.rs/obavestenje"),
        @XmlNs(prefix = "rp", namespaceURI = "http://www.pijz.rs/resenje-ponisteno"),
        @XmlNs(prefix = "rzho", namespaceURI = "http://www.pijz.rs/resenje-zahtev-odbijen"),
        @XmlNs(prefix = "rzn", namespaceURI = "http://www.pijz.rs/resenje-zalba-neosnovana"),
        @XmlNs(prefix = "rzo", namespaceURI = "http://www.pijz.rs/resenje-zalba-osnovana"),
        @XmlNs(prefix = "zc", namespaceURI = "http://www.pijz.rs/zalba-cutanje"),
        @XmlNs(prefix = "zo", namespaceURI = "http://www.pijz.rs/zalba-odluka")
}, elementFormDefault = XmlNsForm.QUALIFIED)
package rs.ijz.server.model;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlNsForm;