//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.18 at 01:26:56 PM CET 
//


package rs.ijz.server.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Tuzba complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tuzba">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rok" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="taksa" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tuzba", propOrder = {
    "rok",
    "taksa"
})
public class Tuzba {

    protected int rok;
    protected double taksa;

    /**
     * Gets the value of the rok property.
     * 
     */
    public int getRok() {
        return rok;
    }

    /**
     * Sets the value of the rok property.
     * 
     */
    public void setRok(int value) {
        this.rok = value;
    }

    /**
     * Gets the value of the taksa property.
     * 
     */
    public double getTaksa() {
        return taksa;
    }

    /**
     * Sets the value of the taksa property.
     * 
     */
    public void setTaksa(double value) {
        this.taksa = value;
    }

}
