//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 09:26:12 PM CET 
//


package rs.pijz.server.poverenik.soap.communication.zahtev;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.pijz.server.poverenik.soap.communication.zahtev package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.pijz.server.poverenik.soap.communication.zahtev
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetZahtevRequest }
     * 
     */
    public GetZahtevRequest createGetZahtevRequest() {
        return new GetZahtevRequest();
    }

    /**
     * Create an instance of {@link GetZahtevResponse }
     * 
     */
    public GetZahtevResponse createGetZahtevResponse() {
        return new GetZahtevResponse();
    }

    /**
     * Create an instance of {@link ExchangeZahtevRequest }
     * 
     */
    public ExchangeZahtevRequest createExchangeZahtevRequest() {
        return new ExchangeZahtevRequest();
    }

    /**
     * Create an instance of {@link ExchangeZahtevResponse }
     * 
     */
    public ExchangeZahtevResponse createExchangeZahtevResponse() {
        return new ExchangeZahtevResponse();
    }

}
