//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.31 at 04:04:59 PM CET 
//


package rs.pijz.server.poverenik.soap.communication.izjasnjenje_na_zalbu;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import rs.pijz.server.poverenik.model.izjasnjenje_na_zalbu.IzjasnjenjeNaZalbu;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="izjasnjenjeNaZalbu" type="{http://www.pijz.rs/izjasnjenje-na-zalbu}IzjasnjenjeNaZalbu"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "izjasnjenjeNaZalbu"
})
@XmlRootElement(name = "getIzjasnjenjeNaZalbuResponse", namespace = "http://www.pijz.rs/izjasnjenje-na-zalbu")
public class GetIzjasnjenjeNaZalbuResponse {

    @XmlElement(namespace = "http://www.pijz.rs/izjasnjenje-na-zalbu", required = true)
    protected IzjasnjenjeNaZalbu izjasnjenjeNaZalbu;

    /**
     * Gets the value of the izjasnjenjeNaZalbu property.
     * 
     * @return
     *     possible object is
     *     {@link IzjasnjenjeNaZalbu }
     *     
     */
    public IzjasnjenjeNaZalbu getIzjasnjenjeNaZalbu() {
        return izjasnjenjeNaZalbu;
    }

    /**
     * Sets the value of the izjasnjenjeNaZalbu property.
     * 
     * @param value
     *     allowed object is
     *     {@link IzjasnjenjeNaZalbu }
     *     
     */
    public void setIzjasnjenjeNaZalbu(IzjasnjenjeNaZalbu value) {
        this.izjasnjenjeNaZalbu = value;
    }

}
