//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.31 at 04:04:59 PM CET 
//


package rs.pijz.server.poverenik.soap.communication.izjasnjenje_na_zalbu;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.pijz.server.poverenik.soap.communication.izjasnjenje_na_zalbu package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.pijz.server.poverenik.soap.communication.izjasnjenje_na_zalbu
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetIzjasnjenjeNaZalbuRequest }
     * 
     */
    public GetIzjasnjenjeNaZalbuRequest createGetIzjasnjenjeNaZalbuRequest() {
        return new GetIzjasnjenjeNaZalbuRequest();
    }

    /**
     * Create an instance of {@link GetIzjasnjenjeNaZalbuResponse }
     * 
     */
    public GetIzjasnjenjeNaZalbuResponse createGetIzjasnjenjeNaZalbuResponse() {
        return new GetIzjasnjenjeNaZalbuResponse();
    }

}
