//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.04 at 10:23:49 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.pijz.rs/zalba", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package rs.pijz.server.poverenik.soap.communication.zalba;
