//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.03 at 09:41:25 PM CET 
//


package rs.pijz.server.poverenik.soap.communication.zalba_cutanje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.pijz.server.poverenik.soap.communication.zalba_cutanje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.pijz.server.poverenik.soap.communication.zalba_cutanje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExchangeZalbaCutanjeRequest }
     * 
     */
    public ExchangeZalbaCutanjeRequest createExchangeZalbaCutanjeRequest() {
        return new ExchangeZalbaCutanjeRequest();
    }

    /**
     * Create an instance of {@link GetZalbaCutanjeResponse }
     * 
     */
    public GetZalbaCutanjeResponse createGetZalbaCutanjeResponse() {
        return new GetZalbaCutanjeResponse();
    }

    /**
     * Create an instance of {@link ExchangeZalbaCutanjeResponse }
     * 
     */
    public ExchangeZalbaCutanjeResponse createExchangeZalbaCutanjeResponse() {
        return new ExchangeZalbaCutanjeResponse();
    }

    /**
     * Create an instance of {@link GetZalbaCutanjeRequest }
     * 
     */
    public GetZalbaCutanjeRequest createGetZalbaCutanjeRequest() {
        return new GetZalbaCutanjeRequest();
    }

}
