//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.01 at 01:34:19 AM CET 
//


package rs.pijz.server.sluzbenik.soap.communication.obavestenje;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.pijz.server.sluzbenik.soap.communication.obavestenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.pijz.server.sluzbenik.soap.communication.obavestenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetObavestenjeResponse }
     * 
     */
    public GetObavestenjeResponse createGetObavestenjeResponse() {
        return new GetObavestenjeResponse();
    }

    /**
     * Create an instance of {@link GetObavestenjeRequest }
     * 
     */
    public GetObavestenjeRequest createGetObavestenjeRequest() {
        return new GetObavestenjeRequest();
    }

}
